/*
 * Automatically generated by Magic.
 */
CREATE TABLE article(
  article_id integer not null primary key autoincrement,
  title text not null,
  content text not null,
  url text not null,
  source text not null
);

