/*
 * Automatically generated by Magic.
 */
create table articles (
  article_id integer not null primary key autoincrement,
  title text not null,
  content text not null,
  url text unique not null,
  source text not null,
  created timestamp not null default current_timestamp
);

create virtual table vss_articles using vss0(
  embedding_vss(1536)
);

