/*
 * Automatically generated by Magic.
 */
CREATE TABLE articles (
  article_id integer not null primary key autoincrement,
  title text not null,
  content text not null,
  url text not null,
  source text not null,
  created timestamp not null default current_timestamp
);
